/**
 * Static catalog. There is no backend in this demo — this module *is* the API.
 * `tint` drives the gradient behind each product's glyph so the UI stays
 * image-free and works offline.
 */
export const products = [
  {
    id: 'p1',
    name: 'Aurora Over-Ear Headphones',
    brand: 'Aurora Audio',
    category: 'Audio',
    price: 249,
    oldPrice: 299,
    rating: 4.8,
    reviews: 1284,
    stock: 12,
    badge: 'Best seller',
    emoji: '🎧',
    tint: '#6366f1',
    blurb: 'Adaptive noise cancelling with 40-hour battery life.',
    description:
      'Three microphones per cup read the room 200 times a second and cancel what you do not want to hear. Memory-foam earcups, USB-C fast charge, and a 40-hour battery that survives the longest flight you can book.',
    specs: [
      ['Driver', '40mm dynamic'],
      ['Battery', '40 hours (ANC on)'],
      ['Charging', 'USB-C, 10 min = 5 hours'],
      ['Weight', '268 g'],
    ],
  },
  {
    id: 'p2',
    name: 'Pulse Buds Pro',
    brand: 'Aurora Audio',
    category: 'Audio',
    price: 129,
    rating: 4.6,
    reviews: 842,
    stock: 40,
    emoji: '🎵',
    tint: '#0ea5e9',
    blurb: 'Tiny in-ears with a case that charges on any pad.',
    description:
      'Six hours per bud, twenty-four in the case, and a transparency mode natural enough to hold a conversation without taking them out.',
    specs: [
      ['Driver', '11mm'],
      ['Battery', '6 h + 18 h case'],
      ['Water rating', 'IPX4'],
      ['Charging', 'USB-C / Qi'],
    ],
  },
  {
    id: 'p3',
    name: 'Nimbus Smart Watch',
    brand: 'Nimbus',
    category: 'Wearables',
    price: 199,
    rating: 4.5,
    reviews: 603,
    stock: 8,
    badge: 'New',
    emoji: '⌚',
    tint: '#14b8a6',
    blurb: 'Always-on AMOLED, seven-day battery, 90 workout modes.',
    description:
      'A 1.4" AMOLED panel you can read in direct sun, blood-oxygen and sleep tracking overnight, and a battery measured in days rather than hours.',
    specs: [
      ['Display', '1.4" AMOLED'],
      ['Battery', '7 days typical'],
      ['Sensors', 'HR, SpO₂, GPS'],
      ['Water rating', '5 ATM'],
    ],
  },
  {
    id: 'p4',
    name: 'Vertex Mechanical Keyboard',
    brand: 'Vertex',
    category: 'Computing',
    price: 159,
    rating: 4.9,
    reviews: 2210,
    stock: 23,
    badge: 'Staff pick',
    emoji: '⌨️',
    tint: '#f59e0b',
    blurb: '75% layout, hot-swap switches, gasket mount.',
    description:
      'Gasket-mounted aluminium body with three layers of foam, so every keypress lands soft and quiet. Hot-swap sockets mean you can change switches without ever touching a soldering iron.',
    specs: [
      ['Layout', '75% (82 keys)'],
      ['Switches', 'Hot-swap, 5-pin'],
      ['Connection', 'USB-C / 2.4 GHz / BT'],
      ['Body', 'CNC aluminium'],
    ],
  },
  {
    id: 'p5',
    name: 'Halo Desk Lamp',
    brand: 'Halo Living',
    category: 'Home',
    price: 89,
    rating: 4.4,
    reviews: 318,
    stock: 55,
    emoji: '💡',
    tint: '#eab308',
    blurb: 'Flicker-free light that follows the time of day.',
    description:
      'A wide light bar that spreads evenly across a desk instead of spotlighting the middle of it, with colour temperature that warms up automatically after sunset.',
    specs: [
      ['Brightness', '800 lumens'],
      ['Colour temp', '2700K – 6000K'],
      ['CRI', 'Ra 95'],
      ['Power', 'USB-C, 12 W'],
    ],
  },
  {
    id: 'p6',
    name: 'Orbit Wireless Mouse',
    brand: 'Vertex',
    category: 'Computing',
    price: 69,
    oldPrice: 89,
    rating: 4.3,
    reviews: 977,
    stock: 31,
    emoji: '🖱️',
    tint: '#8b5cf6',
    blurb: 'Silent clicks, 8K sensor, three-device switching.',
    description:
      'Sculpted for a palm grip, with a magnetic scroll wheel that switches between ratcheted and free-spin the harder you flick it.',
    specs: [
      ['Sensor', '8000 DPI'],
      ['Battery', '70 days'],
      ['Devices', '3 paired at once'],
      ['Weight', '99 g'],
    ],
  },
  {
    id: 'p7',
    name: 'Lumen Mirrorless Camera',
    brand: 'Lumen',
    category: 'Photography',
    price: 1299,
    rating: 4.9,
    reviews: 412,
    stock: 4,
    badge: 'Low stock',
    emoji: '📷',
    tint: '#ef4444',
    blurb: '26MP full-frame body with in-body stabilisation.',
    description:
      'Five-axis stabilisation good for six stops, 4K60 internal recording, and a weather-sealed magnesium body that shrugs off a wet afternoon.',
    specs: [
      ['Sensor', '26MP full-frame'],
      ['Stabilisation', '5-axis, 6 stops'],
      ['Video', '4K60 10-bit'],
      ['Mount', 'Lumen L'],
    ],
  },
  {
    id: 'p8',
    name: 'Drift Portable Speaker',
    brand: 'Aurora Audio',
    category: 'Audio',
    price: 119,
    rating: 4.5,
    reviews: 654,
    stock: 27,
    emoji: '🔊',
    tint: '#3b82f6',
    blurb: 'Floats, survives sand, plays for eighteen hours.',
    description:
      'Passive radiators on both ends give it far more low end than the size suggests, and the whole thing floats face-up if it goes in the water.',
    specs: [
      ['Output', '30 W'],
      ['Battery', '18 hours'],
      ['Rating', 'IP67, floats'],
      ['Pairing', 'Stereo pair of two'],
    ],
  },
  {
    id: 'p9',
    name: 'Ember Espresso Maker',
    brand: 'Ember',
    category: 'Home',
    price: 349,
    oldPrice: 429,
    rating: 4.7,
    reviews: 1105,
    stock: 9,
    badge: '19% off',
    emoji: '☕',
    tint: '#b45309',
    blurb: 'PID-controlled brew temperature and a real steam wand.',
    description:
      'Holds the brew head within half a degree shot after shot, heats up in twenty seconds, and comes with a bottomless portafilter so you can actually see the extraction.',
    specs: [
      ['Pump', '9 bar'],
      ['Heat-up', '20 seconds'],
      ['Water tank', '2 L'],
      ['Portafilter', '58 mm'],
    ],
  },
  {
    id: 'p10',
    name: 'Nova Gaming Controller',
    brand: 'Nova',
    category: 'Gaming',
    price: 79,
    rating: 4.2,
    reviews: 1533,
    stock: 64,
    emoji: '🎮',
    tint: '#22c55e',
    blurb: 'Hall-effect sticks that will not drift.',
    description:
      'Magnetic sticks and triggers with no physical contact to wear out, four remappable back paddles, and a 1000 Hz wireless polling rate.',
    specs: [
      ['Sticks', 'Hall-effect'],
      ['Polling', '1000 Hz'],
      ['Battery', '25 hours'],
      ['Paddles', '4 remappable'],
    ],
  },
  {
    id: 'p11',
    name: 'Atlas Laptop Stand',
    brand: 'Atlas',
    category: 'Computing',
    price: 59,
    rating: 4.6,
    reviews: 288,
    stock: 72,
    emoji: '💻',
    tint: '#64748b',
    blurb: 'Folds flat, holds steady, raises the screen to eye level.',
    description:
      'Single-piece anodised aluminium with silicone pads, six height positions, and a folded profile thin enough to slide into the laptop sleeve it holds.',
    specs: [
      ['Material', 'Anodised aluminium'],
      ['Fits', 'Up to 16"'],
      ['Positions', '6 heights'],
      ['Folded', '1.6 cm thick'],
    ],
  },
  {
    id: 'p12',
    name: 'Zenith VR Headset',
    brand: 'Zenith',
    category: 'Gaming',
    price: 499,
    rating: 4.4,
    reviews: 726,
    stock: 6,
    badge: 'New',
    emoji: '🥽',
    tint: '#d946ef',
    blurb: 'Pancake lenses, 120 Hz, no base stations needed.',
    description:
      'Inside-out tracking with four cameras means no sensors to mount on the wall. Pancake optics keep the front light enough that the weight stays off your cheekbones.',
    specs: [
      ['Resolution', '2064 × 2208 per eye'],
      ['Refresh', '120 Hz'],
      ['Tracking', 'Inside-out, 4 cameras'],
      ['Weight', '515 g'],
    ],
  },
];

export const categories = [...new Set(products.map((p) => p.category))].sort();

export const findProduct = (id) => products.find((p) => p.id === id);
